# Generated by Django 4.2.4 on 2025-02-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='distance_category',
            field=models.CharField(choices=[('0-5', '0-5 km'), ('5-10', '5-10 km'), ('10-15', '10-15 km'), ('15-20', '15-20 km'), ('20-25', '20-25 km'), ('25-30', '25-30 km'), ('30-35', '30-35 km'), ('35-40', '35-40 km'), ('40+', '40+ km')], default='0-5', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='fixed_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='semester',
            field=models.CharField(choices=[('Sem 1', 'Semester 1'), ('Sem 2', 'Semester 2'), ('Sem 3', 'Semester 3'), ('Sem 4', 'Semester 4'), ('Sem 5', 'Semester 5'), ('Sem 6', 'Semester 6'), ('Sem 7', 'Semester 7'), ('Sem 8', 'Semester 8')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
