# Generated by Django 4.2.4 on 2025-02-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_busstop_bus_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registered_id',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('batch_year', models.CharField(max_length=9)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('EC', 'Electronics and Communication'), ('EEE', 'Electrical and Electronics'), ('AD', 'Artificial Intelligence & Data Science')], max_length=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('bus_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bus')),
                ('preferred_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.busstop')),
            ],
        ),
    ]
