# Generated by Django 4.2.4 on 2025-02-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_student_registered_id_studentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='registered_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
