# Generated by Django 4.2.4 on 2025-03-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
