# Generated by Django 4.2.4 on 2025-03-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bus_tracking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
